_wandb:
    value:
        cli_version: 0.21.1
        e:
            diacyxlabazjnw72pd7wpzs16o3wifxo:
                args:
                    - -e
                    - "000"
                    - -s
                    - asl100
                codePath: lukes-code/train_mvit.py
                codePathLocal: train_mvit.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "370608730112"
                        used: "290680311808"
                email: ljgoodall2001@gmail.com
                executable: /home/luke/miniconda3/envs/wlasl/bin/python
                git:
                    commit: 926dc6536f6cbc83d957c8dea2e7d3343beb8226
                    remote: git@github.com:0p3nTheSauce/WLASL.git
                gpu: NVIDIA GeForce GTX 1080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 3584
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce GTX 1080 Ti
                      uuid: GPU-319028de-b377-32bc-7c0c-63b81dd01ad1
                host: luke-PPB660M-C
                memory:
                    total: "16498356224"
                os: Linux-6.8.0-65-generic-x86_64-with-glibc2.35
                program: /home/luke/ExtraStorage/WLASL/lukes-code/train_mvit.py
                python: CPython 3.10.18
                root: /home/luke/ExtraStorage/WLASL/lukes-code
                startedAt: "2025-08-10T23:25:01.871304Z"
                writerId: diacyxlabazjnw72pd7wpzs16o3wifxo
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 2
                - 3
                - 12
                - 41
                - 49
            "2":
                - 1
                - 2
                - 3
                - 12
                - 41
                - 49
            "3":
                - 13
                - 15
                - 16
            "4": 3.10.18
            "5": 0.21.1
            "8":
                - 2
            "12": 0.21.1
            "13": linux-x86_64
ADMIN_experiment:
    value: 0
DATA_frame_size:
    value: 224
DATA_num_frames:
    value: 32
OPTIMIZER_adm_eps:
    value: 0.001
OPTIMIZER_adm_lr:
    value: 0.001
OPTIMIZER_adm_weight_decay:
    value: 1e-07
SCHEDULER_schd_eta_min:
    value: 1e-05
SCHEDULER_schd_tmax:
    value: 100
TRAIN_batch_size:
    value: 6
TRAIN_max_epoch:
    value: 200
TRAIN_max_steps:
    value: 64000
TRAIN_update_per_step:
    value: 1
bs__batch_size:
    value: null
config:
    value: null
config_path:
    value: ./configfiles/asl100/MViT_V2_S_000.ini
exp_no:
    value: "000"
experiment:
    value: 0
fs__frame_size:
    value: null
labels:
    value: ./preprocessed/labels/asl100
max_epoch:
    value: null
max_steps:
    value: null
nf__num_frames:
    value: null
recover:
    value: false
root:
    value: ../data/WLASL2000
save_path:
    value: runs/asl100/MViT_V2_S_exp000/checkpoints/
split:
    value: asl100
us__update_per_step:
    value: null
