[training]
batch_size = 4
update_per_step = 2
max_epoch = 200
batch_size_equivalent = 8

[optimizer]
eps = 1e-05
backbone_init_lr = 0.0001
backbone_weight_decay = 0.001
classifier_init_lr = 0.001
classifier_weight_decay = 0.001

[model_params]
drop_p = 0.5
type = "supervised"

[data]
strict_size = true
target_length = 16
frame_size = 224

[data.train_augs]
normalise = true
temporal_aug = [
    { target_length = 16, max_wobble = 0, type = "og", randomise = false },
]
spatial_aug = [
    { frame_size = 224, type = "Random_crop" },
    { type = "HORIZONTAL_FLIP", p = 0.5 },
]
strict_size = true
target_length = 16
frame_size = 224

[data.train_augs.norm_dict]
mean = [
    0.45,
    0.45,
    0.45,
]
std = [
    0.225,
    0.225,
    0.225,
]

[data.test_augs]
normalise = true
temporal_aug = [
    { target_length = 16, max_wobble = 0, type = "og", randomise = false },
]
spatial_aug = [
    { frame_size = 224, type = "Centre_crop" },
]
strict_size = true
target_length = 16
frame_size = 224

[data.test_augs.norm_dict]
mean = [
    0.45,
    0.45,
    0.45,
]
std = [
    0.225,
    0.225,
    0.225,
]

[early_stopping]
metric = [
    "val",
    "loss",
]
mode = "min"
patience = 50
min_delta = 0.01


# same as configfiles/asl100/MViTv2_S_010.ini but without
# learning rate scheduler
# this actually set the new best loss
# updated by script