"""
Provide functions to accumulate and summarise statistics for the WLASL dataset, including:
- Class-level statistics (book):
		(instances, signers, variations, distributions of : length, source, video)
- Set-level statistics (train/val/test)
- LaTeX table generation for reporting
- Visualisation utilities for exploring the distribution of instances and signers per class.

The structure of the input is directly influenced by the original WLASL JSON format:
- NOTE: For consistency, these methods should be altered to use the format available in preprocessed folder
		 (generated by preprocess.py). This should be simple given they are very similar


Naming convention:
- set: one of train, test and val
- split one of asl100, asl300, asl1000, asl2000

"""

import json
from pathlib import Path
from typing import (
	List,
	Dict,
	TypedDict,
	TypeAlias,
	Literal,
	Optional,
	Union,
	Any,
	Iterable,
	Tuple
)
import matplotlib.pyplot as plt
import numpy as np
# locals
from configs import WLASL_ROOT, SPLIT_DIR, CLASSES_PATH
from preprocess import instance_dict, wlasl_class_dict, InstanceDict

AVAIL_SETS: TypeAlias = Literal["train", "val", "test"]
AVAIL_SPLITS: TypeAlias = Literal["asl100", "asl300", "asl1000", "asl2000"]


class HistoGram(Dict[Any, int]):
	"""Represents a histogram with value : count"""

	pass


def make_histogram(values: Iterable) -> HistoGram:
	"""Add up counts of unique values"""
	hist = HistoGram({})
	for val in values:
		if val in hist:
			hist[val] += 1
		else:
			hist[val] = 1
	return hist


class class_stats(TypedDict):
	"""Represents statistics for a single gloss.
	Keys
	---------
	- num_instances: int
	- length_distribution: HistoGram
	- signers_distribution: HistoGram
	- source_distribution: HistoGram
	- url_distribution: HistoGram
	- variation_distribution: HistoGram
	"""

	num_instances: int
	length_distribution: HistoGram
	signers_distribution: HistoGram
	source_distribution: HistoGram
	url_distribution: HistoGram
	variation_distribution: HistoGram


class set_stats(TypedDict):
	"""Represents statistics for a data subset (train/val/test)."""

	num_instances: int
	num_signers: int
	per_class_stats: Dict[str, class_stats]  # key is the class name


class split_stats(TypedDict):
	"""Represents statistics for a single dataset split (asl100, asl300, asl1000, asl2000)."""

	num_classes: int
	num_instances: int
	num_signers: int
	per_set_stats: Dict[AVAIL_SETS, set_stats]


# SET MANIPULATION


class preproc_class_dict(TypedDict):
	"""Represents a single gloss and its associated instances. Keeps the original
	unprocessed wlasl format, but with the preprocessed dict (added info)

	Keys:
	--------
	- gloss: str
	- instances: List[InstanceDict]
	"""

	gloss: str
	instances: List[InstanceDict]


def reverse_preproc_format(
	preproc_instances: List[InstanceDict],
) -> List[preproc_class_dict]:
	num_classes = len(set([inst["label_name"] for inst in preproc_instances]))
	lst_ppcd = [preproc_class_dict(gloss="empty", instances=[])] * num_classes
	for pp_inst in preproc_instances:
		label_num = pp_inst["label_num"]
		entry = lst_ppcd[label_num]
		if entry["gloss"] == "empty":
			lst_ppcd[label_num] = preproc_class_dict(
				gloss=pp_inst["label_name"], instances=[pp_inst]
			)
		else:
			lst_ppcd[label_num]["instances"].append(pp_inst)

	return lst_ppcd


def get_set(
	instances: List[instance_dict], set_name: AVAIL_SETS
) -> List[instance_dict]:
	"""Filters instances to only include those belonging to a specific set (train/val/test)."""
	filtered_instances = []
	for instance in instances:
		if instance["split"] == set_name:
			filtered_instances.append(instance)
	return filtered_instances


def seperate_by_set(
	glosses: List[wlasl_class_dict],
) -> Dict[AVAIL_SETS, List[wlasl_class_dict]]:
	"""Separates glosses by their set (train/val/test)."""
	set_names: List[AVAIL_SETS] = ["train", "val", "test"]
	sets: Dict[AVAIL_SETS, List[wlasl_class_dict]] = {name: [] for name in set_names}
	for gloss in glosses:
		instances = gloss["instances"]
		for set_name in sets.keys():
			filtered_instances = get_set(instances, set_name)

			sets[set_name].append(
				{"gloss": gloss["gloss"], "instances": filtered_instances}
			)
	return sets


def retrieve_split_data(
	split: AVAIL_SPLITS, labels_dir: Path, pattern: str
) -> Dict[str, Any]:

	split_dir = labels_dir / split
	objects = {}
	for file in split_dir.glob(pattern):
		with open(file, "r") as f:
			objects[file.name] = json.load(f)

	return objects


# STATISTICS CALCULATION


def collect_class_stats(
	instances: Union[List[InstanceDict], List[instance_dict]],
) -> class_stats:
	"""Collects statistics for a single class based on its instances.

	Args:
			instances (List[instance_dict]): A list of instances of the same class

	Returns:
			class_stats: Statistics for the specific class, collected from all its instances
	"""
	num_instances = 0
	histograms = {
		"length": HistoGram({}),
		"signer_id": HistoGram({}),
		"source": HistoGram({}),
		"url": HistoGram({}),
		"variation_id": HistoGram({}),
	}

	for instance in instances:
		num_instances += 1
		instance_with_length = {
			**instance | {"length": instance["frame_end"] - instance["frame_start"]}
		}  # add length key
		for key, hist in histograms.items():  # do for each type of histogram
			value = instance_with_length[key]
			if value in hist:
				hist[value] += 1  # update bin count
			else:
				hist[value] = 1  # create entry if it doesnt exist

	return class_stats(
		num_instances=num_instances,
		length_distribution=histograms["length"],
		signers_distribution=histograms["signer_id"],
		source_distribution=histograms["source"],
		url_distribution=histograms["url"],
		variation_distribution=histograms["variation_id"],
	)


def get_per_class_stats(glosses: List[wlasl_class_dict]) -> Dict[str, class_stats]:
	"""Collects statistics for all classes in a list of wlasl_class_dicts (recommend seperating into test/val/train first)"""
	per_class_stats = {}
	for gloss in glosses:
		class_name = gloss["gloss"]
		instances = gloss["instances"]
		per_class_stats[class_name] = collect_class_stats(instances)
	return per_class_stats


# def collect_all_class_stats(glosses: List[wlasl_class_dict]) -> Dict[str, class_stats]:
#     """Collects statistics for all classes in a list of wlasl_class_dicts (recommend seperating into test/val/train first)"""
#     all_class_stats = {}
#     for gloss_d in glosses:
#         class_name = gloss_d["gloss"]
#         instances = gloss_d["instances"]
#         per_class_stats[class_name] = collect_class_stats(instances)
#     return per_class_stats


def get_unique_signers(dataset: List[wlasl_class_dict]) -> set[int]:
	"""Get set of unique sighners in a list of wlasl_class_dicts"""
	signers = set()
	for gloss_d in dataset:
		for instance_dict in gloss_d["instances"]:
			signers.add(instance_dict["signer_id"])
	return signers


def get_num_instances(dataset: List[wlasl_class_dict]) -> int:
	"""Get the number of instances in a dataset"""

	num_instances = 0
	for gloss_d in dataset:
		num_instances += len(gloss_d["instances"])
	return num_instances


def get_set_stats(subset: List[wlasl_class_dict]) -> set_stats:
	"""Get stats for a particular set (one of test/val.train, seperate first)"""
	return set_stats(
		num_instances=get_num_instances(subset),
		num_signers=len(get_unique_signers(subset)),
		per_class_stats=get_per_class_stats(subset),
	)


def get_per_set_stats(glosses: List[wlasl_class_dict]) -> Dict[AVAIL_SETS, set_stats]:
	"""Seperates into sets, then returns stats per set"""
	sets = seperate_by_set(glosses)
	per_set_stats = {}
	for set_name, glosses_subset in sets.items():
		per_set_stats[set_name] = get_set_stats(glosses_subset)
	return per_set_stats


def get_split_stats(split: List[wlasl_class_dict]) -> split_stats:
	return split_stats(
		num_classes=len(split),
		num_instances=get_num_instances(split),
		num_signers=len(get_unique_signers(split)),
		per_set_stats=get_per_set_stats(split),
	)


# LaTeX TABLE GENERATION

# copilot


def latex_split_summary_table(split_name: AVAIL_SPLITS, stats: split_stats) -> str:
	"""
	Generate a LaTeX table summarising statistics for each set (train/val/test)
	for a given split.

	Parameters
	----------
	split_name : AVAIL_SPLITS
			Name of the dataset split, e.g. "asl100".
	stats : split_stats
			Statistics structure for the split.

	Returns
	-------
	str
			A LaTeX table environment as a string.
	"""

	rows = []
	for set_name, s in stats["per_set_stats"].items():
		rows.append(
			f"{set_name} & {s['num_instances']} & {s['num_signers']} & "
			f"{len(s['per_class_stats'])} \\\\"
		)

	table = (
		r"""
		\begin{table}[h]
		\centering
		\begin{tabular}{lccc}
		\hline
		Set & Instances & Signers & Classes \\
		\hline
		"""
		+ "\n".join(rows)
		+ r"""
		\hline
		\end{tabular}
		\caption{Statistics summary for split %s.}
		\end{table}
		"""
		% split_name
	)

	return table.strip()


# copilot
def latex_class_stats_table(
	split_name: AVAIL_SPLITS,
	set_name: AVAIL_SETS,
	set_stats_obj: set_stats,
) -> str:
	"""
	Generate a LaTeX table listing per-class statistics for a chosen subset.

	Parameters
	----------
	split_name : AVAIL_SPLITS
			Name of the dataset split (e.g., "asl100").
	set_name : AVAIL_SETS
			The subset to summarise (train/val/test).
	set_stats_obj : set_stats
			The statistics object for the chosen set.

	Returns
	-------
	str
			A LaTeX table environment as a string.
	"""
	rows = []
	for gloss, cstats in set_stats_obj["per_class_stats"].items():
		rows.append(
			f"{gloss} & {cstats['num_instances']} & "
			f"{len(cstats['signers_distribution'])} & {len(cstats['variation_distribution'])} \\\\"
		)

	table = (
		r"""
		\begin{table}[h]
		\centering
		\begin{tabular}{lccc}
		\hline
		Gloss & Instances & Signers & Variations \\
		\hline
		"""
		+ "\n".join(rows)
		+ r"""
		\hline
		\end{tabular}
		\caption{Class-level statistics for %s (%s split).}
		\end{table}
		"""
		% (set_name, split_name)
	)

	return table.strip()


# =============================================================================
#                       VISUALISATION HELPERS
# =============================================================================


# 1/2 cluade, 1/2 me
def plot_distribution_o(
	histogram: HistoGram,
	gloss: str,
	set_name: AVAIL_SETS,
	split_name: AVAIL_SPLITS,
	metric: str,
	unit: str = "",
	categorical: bool = False,
) -> None:

	sorted_items = sorted(
		histogram.items(), key=lambda x: str(x[0]) if categorical else x[0]
	)
	# sorted_items = sorted(histogram.items(), key=lambda x: x[0]) #sort by keys
	values, counts = zip(*sorted_items)  # seperate tuples
	expanded_values = [
		value for value, count in sorted_items for _ in range(count)
	]  # un-do binning

	plt.figure(figsize=(12, 4))

	if categorical:
		x_pos = range(len(values))
		plt.bar(
			x_pos, counts, width=0.8
		)  # gapless for quantitative, gaps for categorical
		plt.xticks(x_pos, values, rotation=45, ha="right")
	else:
		plt.bar(values, counts, width=2)
		# plt.hist(expanded_values, bins=30)

		statsy_listy = [
			("mean", lambda x: np.mean(x), "red"),
			("median", lambda x: np.median(x), "blue"),
			("lower quartile", lambda x: np.percentile(x, 25), "brown"),
			("upper quartile", lambda x: np.percentile(x, 75), "brown"),
		]
		for metric_name, stat_func, colour in statsy_listy:
			metric_val = stat_func(expanded_values)
			plt.axvline(
				metric_val,
				color=colour,
				linestyle="--",
				label=f"{metric_name}: {metric_val:.1f}{' ' + unit if unit else ''}",
			)

		plt.legend()

	xlabel = f"{metric}{' (' + unit + ')' if unit else ''}"
	plt.xlabel(xlabel)
	plt.ylabel("Count")
	plt.title(
		f'{metric.capitalize()} Distribution: {split_name} / {set_name} / "{gloss}"'
	)
	plt.tight_layout()
	plt.show()

def plot_distribution(
	histogram: HistoGram,
	gloss: str,
	set_name: AVAIL_SETS,
	split_name: AVAIL_SPLITS,
	metric: str,
	unit: str = "",
	categorical: bool = False,
	hist_or_bar: Literal['hist', 'bar'] = 'hist',
	bins: Optional[int] = None,
	figsize: Tuple[int, int] = (12, 4)
) -> None:

	sorted_items = sorted(
		histogram.items(), key=lambda x: str(x[0]) if categorical else x[0]
	)
	# sorted_items = sorted(histogram.items(), key=lambda x: x[0]) #sort by keys
	values, counts = zip(*sorted_items)  # seperate tuples
	expanded_values = [
		value for value, count in sorted_items for _ in range(count)
	]  # un-do binning

	plt.figure(figsize=figsize)

	if categorical:
		x_pos = range(len(values))
		plt.bar(
			x_pos, counts, width=0.8
		)  # gapless for quantitative, gaps for categorical
		plt.xticks(x_pos, values, rotation=45, ha="right")
	else:
		if hist_or_bar == 'hist':
			plt.hist(expanded_values, bins = bins)
		else:
			plt.bar(values, counts, width=2)

		statsy_listy = [
			("mean", lambda x: np.mean(x), "red"),
			("median", lambda x: np.median(x), "blue"),
			("lower quartile", lambda x: np.percentile(x, 25), "brown"),
			("upper quartile", lambda x: np.percentile(x, 75), "brown"),
		]
		for metric_name, stat_func, colour in statsy_listy:
			metric_val = stat_func(expanded_values)
			plt.axvline(
				metric_val,
				color=colour,
				linestyle="--",
				label=f"{metric_name}: {metric_val:.1f}{' ' + unit if unit else ''}",
			)

		plt.legend()

	xlabel = f"{metric}{' (' + unit + ')' if unit else ''}"
	plt.xlabel(xlabel)
	plt.ylabel("Count")
	plt.title(
		f'{metric.capitalize()} Distribution: {split_name} / {set_name} / "{gloss}"'
	)
	plt.tight_layout()
	plt.show()

# copilot
def barplot_metric(
	per_class: Dict[str, class_stats],
	metric: str,
	top_n: Optional[int] = None,
	title: Optional[str] = None,
	figsize: tuple = (12, 6),
) -> None:
	"""
	Create a bar plot for a chosen metric across glosses.

	Parameters
	----------
	per_class : dict
			Mapping gloss → class_stats.
	metric : str
			One of {"num_instances", "num_signers", "num_variations"}.
	top_n : int, optional
			If provided, only plot the top-N glosses for the chosen metric.
	title : str, optional
			Plot title.
	figsize : tuple
			Matplotlib figure size.
	"""
	if metric not in {"num_instances", "num_signers", "num_variations"}:
		raise ValueError(f"Invalid metric: {metric}")

	# Extract metric values per gloss
	items = [(g, stats[metric]) for g, stats in per_class.items()]
	items.sort(key=lambda x: x[1], reverse=True)

	if top_n:
		items = items[:top_n]

	glosses, values = zip(*items)

	plt.figure(figsize=figsize)
	plt.bar(glosses, values)
	plt.xticks(rotation=90)
	plt.ylabel(metric.replace("_", " ").title())
	if title:
		plt.title(title)
	plt.tight_layout()
	plt.show()


# copilot
def histogram_metric(
	per_class: Dict[str, class_stats],
	metric: str,
	bins: int = 20,
	title: Optional[str] = None,
	figsize: tuple = (8, 5),
) -> None:
	"""
	Plot a histogram of a chosen metric across glosses.

	Parameters
	----------
	per_class : dict
			Mapping gloss → class_stats.
	metric : str
			One of {"num_instances", "num_signers", "num_variations"}.
	bins : int
			Number of histogram bins.
	title : str, optional
			Plot title.
	figsize : tuple
			Matplotlib figure size.
	"""
	if metric not in {"num_instances", "num_signers", "num_variations"}:
		raise ValueError(f"Invalid metric: {metric}")

	values = [stats[metric] for stats in per_class.values()]

	plt.figure(figsize=figsize)
	plt.hist(values, bins=bins)
	plt.xlabel(metric.replace("_", " ").title())
	plt.ylabel("Frequency")
	if title:
		plt.title(title)
	plt.tight_layout()
	plt.show()


# copilot
def scatter_instances_vs_signers(
	per_class: Dict[str, class_stats],
	figsize: tuple = (6, 5),
	title: Optional[str] = None,
) -> None:
	"""
	Scatter plot of num_instances vs num_signers for each gloss.

	Parameters
	----------
	per_class : dict
			Mapping gloss → class_stats.
	figsize : tuple
			Figure size.
	title : str, optional
			Plot title.
	"""
	x = [c["num_instances"] for c in per_class.values()]
	y = [len(c["signers_distribution"]) for c in per_class.values()]

	plt.figure(figsize=figsize)
	plt.scatter(x, y, alpha=0.7)
	plt.xlabel("Number of Instances")
	plt.ylabel("Number of Signers")
	if title:
		plt.title(title)
	plt.tight_layout()
	plt.show()


if __name__ == "__main__":
	objects = retrieve_split_data(
		split="asl100",
		labels_dir=Path("/home/luke/Code/SLR/code/preprocessed/labels_new"),
		pattern="*_instances*.json",
	)
	for key, value in objects.items():
		print(f"key: {key} type value: {type(value)}")
