[training]
batch_size = 8
update_per_step = 1
max_epoch = 200
batch_size_equivalent = 8

[optimizer]
eps = 1e-05
backbone_init_lr = 0.0001
backbone_weight_decay = 0.001
classifier_init_lr = 0.001
classifier_weight_decay = 0.001

[model_params]
drop_p = 0.5
type = "supervised"

[data]
strict_size = true
target_length = 32
frame_size = 224

[data.train_augs]
normalise = true
temporal_aug = [
    { target_length = 32, max_wobble = 0, type = "chunked" },
]
spatial_aug = [
    { frame_size = 224, type = "Random_crop" },
    { type = "HORIZONTAL_FLIP", p = 0.5 },
]
strict_size = true
target_length = 32
frame_size = 224

[data.train_augs.norm_dict]
mean = [
    0.43216,
    0.394666,
    0.37645,
]
std = [
    0.22803,
    0.22145,
    0.216989,
]

[data.test_augs]
normalise = true
temporal_aug = [
    { target_length = 32, max_wobble = 0, type = "uniform" },
]
spatial_aug = [
    { frame_size = 224, type = "Centre_crop" },
]
strict_size = true
target_length = 32
frame_size = 224

[data.test_augs.norm_dict]
mean = [
    0.43216,
    0.394666,
    0.37645,
]
std = [
    0.22803,
    0.22145,
    0.216989,
]

[scheduler]
type = "CosineAnnealingWarmRestarts"
t0 = 20
tmult = 1
eta_min = 0.0

[stopping]
type = "early_stopper"
metric = "loss"
phase = "val"
mode = "min"
patience = 15
min_delta = 0.01


# same scheduler as exp47
# matches previos best except with chunked frame sampler and wobble
# and lower patience
# updated by script
# updated by script
# updated by script