[training]
batch_size = 2
update_per_step = 4
max_epoch = 200

[optimizer]
eps = 1e-8
backbone_init_lr = 1e-4
backbone_weight_decay = 0.05
classifier_init_lr = 1e-4
classifier_weight_decay = 0.05

[model_params]
type = "mvir_ted_mae"

[data.train_augs]
normalise = true

[[data.train_augs.temporal_aug]]
type = "og"
target_length = 32

[[data.train_augs.spatial_aug]]
type = "Random_crop"
frame_size = 224

[[data.train_augs.spatial_aug]]
type = "HORIZONTAL_FLIP"
p = 0.5

[data.test_augs]
normalise = true

[[data.test_augs.temporal_aug]]
type = "og"
target_length = 32

[[data.test_augs.spatial_aug]]
type = "Centre_crop"
frame_size = 224

[scheduler]
type = "CosineAnnealingWarmRestarts"
t0 = 10
tmult = 2
eta_min = 1e-6

[early_stopping]
metric = ['val', 'loss']
mode = 'min'
patience = 15
min_delta = 0.01

#Same as /home/luke/Code/SLR/code/configfiles/asl100/MViTv2_S/exp011.ini
# but with MViTv2_B32x3 and updated augmentations
# and patience = 15
