[training]
batch_size = 2
update_per_step = 4
max_epoch = 200

[optimizer]
eps = 1e-5
backbone_init_lr = 1e-4
backbone_weight_decay = 1e-3
classifier_init_lr = 1e-3
classifier_weight_decay = 1e-3

[model_params]

drop_p = 0.5


#Train augs

[data.train_augs]
normalise = true

[[data.train_augs.temporal_aug]]
type = "og"
target_length = 32


[[data.train_augs.spatial_aug]]
type = "HORIZONTAL_FLIP"
p = 0.5

[[data.train_augs.spatial_aug]]
type = "Centre_crop"
frame_size = 224


[[data.train_augs.spatial_aug]]
type = "RANDAUGMENT"
num_ops = 2
magnitude = 7
num_magnitude_bins = 31
interpolation = "bilinear"




#Test augs

[data.test_augs]
normalise = true

[[data.test_augs.temporal_aug]]
type = "og"
target_length = 32

[[data.test_augs.spatial_aug]]
type = "Centre_crop"
frame_size = 224


[scheduler]
type = "CosineAnnealingWarmRestarts"
t0 = 10
tmult = 1
eta_min = 0.0

[early_stopping]
metric = ['val', 'loss']
mode = 'min'
patience = 50
min_delta = 0.01

#Same as /home/luke/Code/SLR/code/configfiles/asl100/MViTv2_S/exp011.ini
# but with MViTv2_B32x3 and updated augmentations
# and patience = 15
