[training]
batch_size = 1
update_per_step = 8
max_epoch = 200
batch_size_equivalent = 8

[optimizer]
eps = 1e-05
backbone_init_lr = 0.0001
backbone_weight_decay = 0.001
classifier_init_lr = 0.001
classifier_weight_decay = 0.001

[model_params]
drop_p = 0.5
type = "supervised"

[data]
strict_size = true
target_length = 32
frame_size = 224

[data.train_augs]
normalise = true
temporal_aug = [
    { target_length = 32, max_wobble = 0, type = "focal_normal", mean = 0.5, std = 0.3 },
]
spatial_aug = [
    { frame_size = 224, type = "Random_crop" },
    { type = "HORIZONTAL_FLIP", p = 0.5 },
]
strict_size = true
target_length = 32
frame_size = 224

[data.train_augs.norm_dict]
mean = [
    0.45,
    0.45,
    0.45,
]
std = [
    0.225,
    0.225,
    0.225,
]

[data.test_augs]
normalise = true
temporal_aug = [
    { target_length = 32, max_wobble = 0, type = "focal_normal", mean = 0.5, std = 0.3 },
]
spatial_aug = [
    { frame_size = 224, type = "Centre_crop" },
]
strict_size = true
target_length = 32
frame_size = 224

[data.test_augs.norm_dict]
mean = [
    0.45,
    0.45,
    0.45,
]
std = [
    0.225,
    0.225,
    0.225,
]

[scheduler]
type = "CosineAnnealingWarmRestarts"
t0 = 10
tmult = 2
eta_min = 0.0

[early_stopping]
metric = [
    "val",
    "loss",
]
mode = "min"
patience = 15
min_delta = 0.01


# Same as exp005
# just with updated augs
# updated by script