wandb_version: 1

data.train_augs.spatial_aug.2.magnitude:
  value: 12
data.train_augs.temporal_aug.0.max_wobble:
  value: 2
model_params.drop_p:
  value: 0.3
optimizer.backbone_init_lr:
  value: 0.0001549529710867987
optimizer.backbone_weight_decay:
  value: 0.0004996263794802689
optimizer.classifier_init_lr:
  value: 0.0004065524120340433
optimizer.classifier_weight_decay:
  value: 0.001814098085178176
scheduler.t0:
  value: 20
