"""
Provide functions to accumulate and summarise statistics for the WLASL dataset, including:
- Class-level statistics (book):
				(instances, signers, variations, distributions of : length, source, video)
- Set-level statistics (train/val/test)
- LaTeX table generation for reporting
- Visualisation utilities for exploring the distribution of instances and signers per class.

The structure of the input is directly influenced by the original WLASL JSON format:
- NOTE: For consistency, these methods should be altered to use the format available in preprocessed folder
				 (generated by preprocess.py). This should be simple given they are very similar


Naming convention:
- set: one of train, test and val
- split one of asl100, asl300, asl1000, asl2000

"""

import json
import logging
from collections.abc import Callable, Iterable
from pathlib import Path
from typing import (
	Any,
	Literal,
	TypeAlias,
	TypedDict,
)

import pandas as pd

from src.configs import get_class_list

# locals
from src.preprocess import Instance, RawInstance, WLASLClass
from src.run_types import AVAIL_SETS, AVAIL_SPLITS
from src.video_dataset import get_labels_path, get_wlasl_info, load_data_from_json

stats_logger = logging.getLogger(__name__)

INSTANCE_KEYS: TypeAlias = Literal[
	"bbox",
	"frame_end",
	"frame_start",
	"instance_id",
	"signer_id",
	"source",
	"split",
	"url",
	"variation_id",
	"video_id",
	"label_num",
	"label_name",
]



def sort_distribution(distribution: dict, key=lambda x: x[1]) -> dict:
	return {k: v for k, v in sorted(distribution.items(), key=key)}


def get_n(
	distribution: dict, n: int, key=lambda x: x[1], start_index: int = 0, step: int = 1
) -> dict:
	return {
		k: v
		for k, v in list(sorted(distribution.items(), key=key))[
			start_index : start_index + n : step
		]
	}


class HistoGram(dict[Any, int]):
	"""Represents a histogram with value : count"""



def make_histogram(values: Iterable) -> HistoGram:
	"""Add up counts of unique values"""
	hist = HistoGram({})
	for val in values:
		if val in hist:
			hist[val] += 1
		else:
			hist[val] = 1
	return hist


class instance_stats(TypedDict):
	"""Represents statistics for instances in a list of Instances.
	This can be stats per-class in a set, or, stats for the whole set.
	Keys
	---------
	- num_instances: int
	- length_distribution: HistoGram
	- signers_distribution: HistoGram
	- source_distribution: HistoGram
	- url_distribution: HistoGram
	- variation_distribution: HistoGram
	"""

	num_instances: int
	length_distribution: HistoGram
	signers_distribution: HistoGram
	source_distribution: HistoGram
	url_distribution: HistoGram
	variation_distribution: HistoGram


class set_stats(TypedDict):
	"""Represents statistics for a data subset (train/val/test)."""

	num_instances: int
	num_signers: int
	per_instance_stats: dict[str, instance_stats]  # key is the class name


class split_stats(TypedDict):
	"""Represents statistics for a single dataset split (asl100, asl300, asl1000, asl2000)."""

	num_classes: int
	num_instances: int
	num_signers: int
	per_set_stats: dict[AVAIL_SETS, set_stats]


# SET MANIPULATION


class preproc_class_dict(TypedDict):
	"""Represents a single gloss and its associated instances. Keeps the original
	unprocessed wlasl format, but with the preprocessed dict (added info)

	Keys:
	--------
	- gloss: str
	- instances: List[Instance]
	"""

	gloss: str
	instances: list[Instance]


def reverse_preproc_format(
	preproc_instances: list[Instance],
	classes: list[str] | None = None,
) -> list[preproc_class_dict]:
	"""Convert from flat preprocessed format to original class seperated format"""
	num_classes = len({inst.label_num for inst in preproc_instances})
	lst_ppcd = [preproc_class_dict(gloss="empty", instances=[])] * num_classes
	for pp_inst in preproc_instances:
		label_num = pp_inst.label_num
		entry = lst_ppcd[label_num]
		if entry["gloss"] == "empty":
			if hasattr(pp_inst, "label_name"):
				# if "label_name" in pp_inst:
				gloss = pp_inst.label_name
			elif classes is not None:
				gloss = classes[pp_inst.label_num]
			else:
				raise ValueError("instance does not contain the key: label_name")
			lst_ppcd[label_num] = preproc_class_dict(gloss=gloss, instances=[pp_inst])
		else:
			lst_ppcd[label_num]["instances"].append(pp_inst)

	return lst_ppcd



def _ident(_):
	return True

def to_preproc_format(
	gloss_seperated_instances: list[preproc_class_dict],
	criterion: Callable[[preproc_class_dict], bool] = _ident,
) -> list[Instance]:
	"""Undo reverse_preproc_format, converting from class seperated format to flat preprocessed format"""
	preproc_instances = []
	for gloss in gloss_seperated_instances:
		if criterion(gloss):
			preproc_instances.extend(gloss["instances"])
	return preproc_instances


def get_set(instances: list[RawInstance], set_name: AVAIL_SETS) -> list[RawInstance]:
	"""Filters instances to only include those belonging to a specific set (train/val/test)."""
	filtered_instances = []
	for instance in instances:
		if instance.split == set_name:
			filtered_instances.append(instance)
	return filtered_instances


def seperate_by_set(
	glosses: list[WLASLClass],
) -> dict[AVAIL_SETS, list[WLASLClass]]:
	"""Separates glosses by their set (train/val/test)."""
	set_names: list[AVAIL_SETS] = ["train", "val", "test"]
	sets: dict[AVAIL_SETS, list[WLASLClass]] = {name: [] for name in set_names}
	for gloss in glosses:
		instances = gloss.instances
		for set_name, set_val in sets.items():
			filtered_instances = get_set(instances, set_name)

			set_val.append(
				WLASLClass.model_validate(
					{"gloss": gloss.gloss, "instances": filtered_instances}
				)
			)
	return sets


def retrieve_split_data(
	split: AVAIL_SPLITS, labels_dir: Path, pattern: str
) -> dict[str, Any]:

	split_dir = labels_dir / split
	objects = {}
	for file in split_dir.glob(pattern):
		with open(file, "r") as f:
			objects[file.name] = json.load(f)

	return objects


def get_all_sets(
	split_name: AVAIL_SPLITS,
	set_options: list[AVAIL_SETS] | None = None,  # type: ignore
	classes: list[str] | None = None,
	logger: logging.Logger = stats_logger,
) -> dict[str, list[preproc_class_dict]]:
	"""Load a particular set (e.g. asl100) into a dictionary with the available sets as keys.
	The values, are in the original WLASL format. 
	"""
	if set_options is None:
		set_options = ["train", "test", "val"]
	if classes is None:
		classes = get_class_list()
	all_sets = {}
	for set_name in set_options:
		set_path_info = get_wlasl_info(split_name, set_name)
		set_path = get_labels_path(
			set_name, set_path_info["labels"], set_path_info["label_suff"]
		)
		all_sets[set_name] = reverse_preproc_format(
			load_data_from_json(set_path, policy="strict"), classes
		)
		logger.debug(f"Num classes of {set_name}: {len(all_sets[set_name])}")

	return all_sets


# STATISTICS CALCULATION


def collect_instance_stats(
	instances: list[Instance] | list[RawInstance],
) -> instance_stats:
	"""Collects statistics for a single class based on its instances.

	Args:
					instances (List[RawInstance]): A list of instances of the same class

	Returns:
					instance_stats: Statistics for the specific class, collected from all its instances
	"""
	num_instances = 0
	histograms = {
		"length": HistoGram({}),
		"signer_id": HistoGram({}),
		"source": HistoGram({}),
		"url": HistoGram({}),
		"variation_id": HistoGram({}),
	}

	for instance in instances:
		num_instances += 1
		instance_with_length = {
			**instance.model_dump()
			| {"length": instance.frame_end - instance.frame_start}
		}  # add length key

		for key, hist in histograms.items():  # do for each type of histogram
			value = instance_with_length[key]
			if value in hist:
				hist[value] += 1  # update bin count
			else:
				hist[value] = 1  # create entry if it doesnt exist

	return instance_stats(
		num_instances=num_instances,
		length_distribution=histograms["length"],
		signers_distribution=histograms["signer_id"],
		source_distribution=histograms["source"],
		url_distribution=histograms["url"],
		variation_distribution=histograms["variation_id"],
	)


def get_per_instance_stats(glosses: list[WLASLClass]) -> dict[str, instance_stats]:
	"""Collects statistics for all classes in a list of WLASLClasss (recommend seperating into test/val/train first)"""
	per_instance_stats = {}
	for gloss in glosses:
		class_name = gloss.gloss
		instances = gloss.instances
		per_instance_stats[class_name] = collect_instance_stats(instances)
	return per_instance_stats


def get_unique_signers(dataset: list[WLASLClass]) -> set[int]:
	"""Get set of unique sighners in a list of WLASLClasss"""
	signers = set()
	for gloss_d in dataset:
		for instance_d in gloss_d.instances:
			signers.add(instance_d.signer_id)
	return signers


def get_num_instances(dataset: list[WLASLClass]) -> int:
	"""Get the number of instances in a dataset"""

	num_instances = 0
	for gloss_d in dataset:
		num_instances += len(gloss_d.instances)
	return num_instances


def get_set_stats(subset: list[WLASLClass]) -> set_stats:
	"""Get stats for a particular set (one of test/val.train, seperate first)"""
	return set_stats(
		num_instances=get_num_instances(subset),
		num_signers=len(get_unique_signers(subset)),
		per_instance_stats=get_per_instance_stats(subset),
	)


def get_per_set_stats(glosses: list[WLASLClass]) -> dict[AVAIL_SETS, set_stats]:
	"""Seperates into sets, then returns stats per set"""
	sets = seperate_by_set(glosses)
	per_set_stats = {}
	for set_name, glosses_subset in sets.items():
		per_set_stats[set_name] = get_set_stats(glosses_subset)
	return per_set_stats


def get_split_stats(split: list[WLASLClass]) -> split_stats:
	return split_stats(
		num_classes=len(split),
		num_instances=get_num_instances(split),
		num_signers=len(get_unique_signers(split)),
		per_set_stats=get_per_set_stats(split),
	)


# -----------------------------------------------------------------------------------------------------------
# correlation_f1_instances.ipynb:
# -----------------------------------------------------------------------------------------------------------

def get_min_max_num_instances(per_instance_stats: dict[str, instance_stats]) -> tuple[int, int]:
    """Returns the minumum and maximum number of instances in a dictionary of instance stats

    Args:
        per_instance_stats (Dict[str, stats.instance_stats]): A dictionary with stats for each class indexed by label_name

    Returns:
        Tuple[int, int]: min, max number of instances.
    """
    mini = float('inf')
    maxi = float(0)
    for inst_stats in per_instance_stats.values():
        num_inst = inst_stats['num_instances']
        maxi = max(maxi, num_inst)
        mini = min(mini, num_inst)
    return int(mini), int(maxi) 

def get_min_max_num_signers(per_instance_stats: dict[str, instance_stats]) -> tuple[int, int]:
    """Returns the minumum and maximum number of signers in a dictionary of instance stats

    Args:
        per_instance_stats (Dict[str, stats.instance_stats]): A dictionary with stats for each class indexed by label_name

    Returns:
        Tuple[int, int]: min, max number of signers.
    """
    mini = float('inf')
    maxi = float(0)
    for inst_stats in per_instance_stats.values():
        num_signers = len(inst_stats['signers_distribution'])
        maxi = max(maxi, num_signers)
        mini = min(mini, num_signers)
    return int(mini), int(maxi) 

def create_instances_table(per_set_stats: dict[AVAIL_SETS, set_stats]) -> pd.DataFrame:
    rows = []
    for set_name, set_stats in per_set_stats.items():
        mini_i, maxi_i = get_min_max_num_instances(set_stats['per_instance_stats'])
        mini_s, maxi_s = get_min_max_num_signers(set_stats['per_instance_stats'])
        rows.append({
            'Set name': set_name,
            'Num instances': set_stats['num_instances'],
            'Num signers': set_stats['num_signers'],
            'instances per gloss': f'[{mini_i} - {maxi_i}]',
            'signers per gloss': f'[{mini_s} - {maxi_s}]'
        })

    return pd.DataFrame(rows)
    



if __name__ == "__main__":
	objects = retrieve_split_data(
		split="asl100",
		labels_dir=Path("/home/luke/Code/SLR/code/preprocessed/labels_new"),
		pattern="*_instances*.json",
	)
	for key, value in objects.items():
		print(f"key: {key} type value: {type(value)}")
