"""
Provide functions to accumulate and summarise statistics for the WLASL dataset, including:
- Class-level statistics (book):
				(instances, signers, variations, distributions of : length, source, video)
- Set-level statistics (train/val/test)
- LaTeX table generation for reporting
- Visualisation utilities for exploring the distribution of instances and signers per class.

The structure of the input is directly influenced by the original WLASL JSON format:
- NOTE: For consistency, these methods should be altered to use the format available in preprocessed folder
				 (generated by preprocess.py). This should be simple given they are very similar


Naming convention:
- set: one of train, test and val
- split one of asl100, asl300, asl1000, asl2000

"""

import json
from pathlib import Path
from typing import (
	List,
	Dict,
	TypedDict,
	TypeAlias,
	Literal,
	Optional,
	Union,
	Any,
	Iterable,
	Callable,
)
import logging

# locals
from src.preprocess import RawInstance, WLASLClass, Instance
from src.run_types import AVAIL_SETS, AVAIL_SPLITS
from src.video_dataset import get_labels_path, load_data_from_json, get_wlasl_info
from src.configs import get_class_list


stats_logger = logging.getLogger(__name__)

INSTANCE_KEYS: TypeAlias = Literal[
	"bbox",
	"frame_end",
	"frame_start",
	"instance_id",
	"signer_id",
	"source",
	"split",
	"url",
	"variation_id",
	"video_id",
	"label_num",
	"label_name",
]



def sort_distribution(distribution: dict, key=lambda x: x[1]) -> dict:
	return {k: v for k, v in sorted(distribution.items(), key=key)}


def get_n(
	distribution: dict, n: int, key=lambda x: x[1], start_index: int = 0, step: int = 1
) -> dict:
	return {
		k: v
		for k, v in list(sorted(distribution.items(), key=key))[
			start_index : start_index + n : step
		]
	}


class HistoGram(Dict[Any, int]):
	"""Represents a histogram with value : count"""

	pass


def make_histogram(values: Iterable) -> HistoGram:
	"""Add up counts of unique values"""
	hist = HistoGram({})
	for val in values:
		if val in hist:
			hist[val] += 1
		else:
			hist[val] = 1
	return hist


class instance_stats(TypedDict):
	"""Represents statistics for instances in a list of Instances.
	This can be stats per-class in a set, or, stats for the whole set.
	Keys
	---------
	- num_instances: int
	- length_distribution: HistoGram
	- signers_distribution: HistoGram
	- source_distribution: HistoGram
	- url_distribution: HistoGram
	- variation_distribution: HistoGram
	"""

	num_instances: int
	length_distribution: HistoGram
	signers_distribution: HistoGram
	source_distribution: HistoGram
	url_distribution: HistoGram
	variation_distribution: HistoGram


class set_stats(TypedDict):
	"""Represents statistics for a data subset (train/val/test)."""

	num_instances: int
	num_signers: int
	per_instance_stats: Dict[str, instance_stats]  # key is the class name


class split_stats(TypedDict):
	"""Represents statistics for a single dataset split (asl100, asl300, asl1000, asl2000)."""

	num_classes: int
	num_instances: int
	num_signers: int
	per_set_stats: Dict[AVAIL_SETS, set_stats]


# SET MANIPULATION


class preproc_class_dict(TypedDict):
	"""Represents a single gloss and its associated instances. Keeps the original
	unprocessed wlasl format, but with the preprocessed dict (added info)

	Keys:
	--------
	- gloss: str
	- instances: List[Instance]
	"""

	gloss: str
	instances: List[Instance]


def reverse_preproc_format(
	preproc_instances: List[Instance],
	classes: Optional[List[str]] = None,
) -> List[preproc_class_dict]:
	"""Convert from flat preprocessed format to original class seperated format"""
	num_classes = len(set([inst.label_num for inst in preproc_instances]))
	lst_ppcd = [preproc_class_dict(gloss="empty", instances=[])] * num_classes
	for pp_inst in preproc_instances:
		label_num = pp_inst.label_num
		entry = lst_ppcd[label_num]
		if entry["gloss"] == "empty":
			if hasattr(pp_inst, "label_name"):
				# if "label_name" in pp_inst:
				gloss = pp_inst.label_name
			elif classes is not None:
				gloss = classes[pp_inst.label_num]
			else:
				raise ValueError("instance does not contain the key: label_name")
			lst_ppcd[label_num] = preproc_class_dict(gloss=gloss, instances=[pp_inst])
		else:
			lst_ppcd[label_num]["instances"].append(pp_inst)

	return lst_ppcd



def _ident(_):
	return True

def to_preproc_format(
	gloss_seperated_instances: List[preproc_class_dict],
	criterion: Callable[[preproc_class_dict], bool] = _ident,
) -> List[Instance]:
	"""Undo reverse_preproc_format, converting from class seperated format to flat preprocessed format"""
	preproc_instances = []
	for gloss in gloss_seperated_instances:
		if criterion(gloss):
			preproc_instances.extend(gloss["instances"])
	return preproc_instances


def get_set(instances: List[RawInstance], set_name: AVAIL_SETS) -> List[RawInstance]:
	"""Filters instances to only include those belonging to a specific set (train/val/test)."""
	filtered_instances = []
	for instance in instances:
		if instance.split == set_name:
			filtered_instances.append(instance)
	return filtered_instances


def seperate_by_set(
	glosses: List[WLASLClass],
) -> Dict[AVAIL_SETS, List[WLASLClass]]:
	"""Separates glosses by their set (train/val/test)."""
	set_names: List[AVAIL_SETS] = ["train", "val", "test"]
	sets: Dict[AVAIL_SETS, List[WLASLClass]] = {name: [] for name in set_names}
	for gloss in glosses:
		instances = gloss.instances
		for set_name in sets.keys():
			filtered_instances = get_set(instances, set_name)

			sets[set_name].append(
				WLASLClass.model_validate(
					{"gloss": gloss.gloss, "instances": filtered_instances}
				)
			)
	return sets


def retrieve_split_data(
	split: AVAIL_SPLITS, labels_dir: Path, pattern: str
) -> Dict[str, Any]:

	split_dir = labels_dir / split
	objects = {}
	for file in split_dir.glob(pattern):
		with open(file, "r") as f:
			objects[file.name] = json.load(f)

	return objects


def get_all_sets(
	split_name: AVAIL_SPLITS,
	set_options: List[AVAIL_SETS] = ["train", "test", "val"],  # type: ignore
	classes: List[str] = get_class_list(),
	logger: logging.Logger = stats_logger,
) -> dict[str, list[preproc_class_dict]]:
	"""Load a particular set (e.g. asl100) into a dictionary with the available sets as keys.
	The values, are in the original WLASL format. 
	"""
	all_sets = {}
	for set_name in set_options:
		set_path_info = get_wlasl_info(split_name, set_name)
		set_path = get_labels_path(
			set_name, set_path_info["labels"], set_path_info["label_suff"]
		)
		all_sets[set_name] = reverse_preproc_format(
			load_data_from_json(set_path, policy="strict"), classes
		)
		logger.debug(f"Num classes of {set_name}: {len(all_sets[set_name])}")

	return all_sets


# STATISTICS CALCULATION


def collect_instance_stats(
	instances: Union[List[Instance], List[RawInstance]],
) -> instance_stats:
	"""Collects statistics for a single class based on its instances.

	Args:
					instances (List[RawInstance]): A list of instances of the same class

	Returns:
					instance_stats: Statistics for the specific class, collected from all its instances
	"""
	num_instances = 0
	histograms = {
		"length": HistoGram({}),
		"signer_id": HistoGram({}),
		"source": HistoGram({}),
		"url": HistoGram({}),
		"variation_id": HistoGram({}),
	}

	for instance in instances:
		num_instances += 1
		instance_with_length = {
			**instance.model_dump()
			| {"length": instance.frame_end - instance.frame_start}
		}  # add length key

		for key, hist in histograms.items():  # do for each type of histogram
			value = instance_with_length[key]
			if value in hist:
				hist[value] += 1  # update bin count
			else:
				hist[value] = 1  # create entry if it doesnt exist

	return instance_stats(
		num_instances=num_instances,
		length_distribution=histograms["length"],
		signers_distribution=histograms["signer_id"],
		source_distribution=histograms["source"],
		url_distribution=histograms["url"],
		variation_distribution=histograms["variation_id"],
	)


def get_per_instance_stats(glosses: List[WLASLClass]) -> Dict[str, instance_stats]:
	"""Collects statistics for all classes in a list of WLASLClasss (recommend seperating into test/val/train first)"""
	per_instance_stats = {}
	for gloss in glosses:
		class_name = gloss.gloss
		instances = gloss.instances
		per_instance_stats[class_name] = collect_instance_stats(instances)
	return per_instance_stats


def get_unique_signers(dataset: List[WLASLClass]) -> set[int]:
	"""Get set of unique sighners in a list of WLASLClasss"""
	signers = set()
	for gloss_d in dataset:
		for instance_d in gloss_d.instances:
			signers.add(instance_d.signer_id)
	return signers


def get_num_instances(dataset: List[WLASLClass]) -> int:
	"""Get the number of instances in a dataset"""

	num_instances = 0
	for gloss_d in dataset:
		num_instances += len(gloss_d.instances)
	return num_instances


def get_set_stats(subset: List[WLASLClass]) -> set_stats:
	"""Get stats for a particular set (one of test/val.train, seperate first)"""
	return set_stats(
		num_instances=get_num_instances(subset),
		num_signers=len(get_unique_signers(subset)),
		per_instance_stats=get_per_instance_stats(subset),
	)


def get_per_set_stats(glosses: List[WLASLClass]) -> Dict[AVAIL_SETS, set_stats]:
	"""Seperates into sets, then returns stats per set"""
	sets = seperate_by_set(glosses)
	per_set_stats = {}
	for set_name, glosses_subset in sets.items():
		per_set_stats[set_name] = get_set_stats(glosses_subset)
	return per_set_stats


def get_split_stats(split: List[WLASLClass]) -> split_stats:
	return split_stats(
		num_classes=len(split),
		num_instances=get_num_instances(split),
		num_signers=len(get_unique_signers(split)),
		per_set_stats=get_per_set_stats(split),
	)



if __name__ == "__main__":
	objects = retrieve_split_data(
		split="asl100",
		labels_dir=Path("/home/luke/Code/SLR/code/preprocessed/labels_new"),
		pattern="*_instances*.json",
	)
	for key, value in objects.items():
		print(f"key: {key} type value: {type(value)}")
