_wandb:
    value:
        cli_version: 0.21.1
        e:
            5jnogtfqk2tl7k5juvg9ijcab16u53zp:
                args:
                    - -e
                    - "0"
                    - -s
                    - asl100
                codePath: lukes-code/train_mvit.py
                codePathLocal: train_mvit.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "370608730112"
                        used: "289631686656"
                email: ljgoodall2001@gmail.com
                executable: /home/luke/miniconda3/envs/wlasl/bin/python
                git:
                    commit: 25927e402c42cec4ae2dff1298e24606c9ab9574
                    remote: git@github.com:0p3nTheSauce/WLASL.git
                gpu: NVIDIA GeForce GTX 1080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 3584
                      memoryTotal: "11811160064"
                      name: NVIDIA GeForce GTX 1080 Ti
                      uuid: GPU-319028de-b377-32bc-7c0c-63b81dd01ad1
                host: luke-PPB660M-C
                memory:
                    total: "16498356224"
                os: Linux-6.8.0-65-generic-x86_64-with-glibc2.35
                program: /home/luke/ExtraStorage/WLASL/lukes-code/train_mvit.py
                python: CPython 3.10.18
                root: /home/luke/ExtraStorage/WLASL/lukes-code
                startedAt: "2025-08-11T10:53:02.017233Z"
                writerId: 5jnogtfqk2tl7k5juvg9ijcab16u53zp
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 2
                - 3
                - 12
                - 41
                - 49
            "2":
                - 1
                - 2
                - 3
                - 12
                - 41
                - 49
            "3":
                - 13
                - 15
                - 16
            "4": 3.10.18
            "5": 0.21.1
            "8":
                - 2
            "12": 0.21.1
            "13": linux-x86_64
admin:
    value:
        config_path: ./configfiles/asl100/MViT_V2_S_000.ini
        exp_no: "000"
        labels: ./preprocessed/labels/asl100
        model: MViT_V2_S
        root: ../data/WLASL2000
        save_path: runs/asl100/MViT_V2_S_exp000/checkpoints
        split: asl100
data:
    value:
        frame_size: 224
        num_frames: 32
optimizer:
    value:
        eps: 0.001
        lr: 0.001
        weight_decay: 1e-07
scheduler:
    value:
        eta_min: 1e-05
        tmax: 100
training:
    value:
        batch_size: 4
        max_epoch: 200
        max_steps: 64000
        update_per_step: 2
